# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4572911e1b20acd63ed4ef7f31722958f7f55b1497f1a0d07a34d79c53ce642746deba4380fba783bf66d71aa2b0148a2bafc9a991352163b99ddd1a2bed98db

test:
  secret_key_base: f60d1d198a0d8e8ad713d75a735ded38061dcda94dba6d17c4bb5207b41d2d3484b95ee85b45251af9745dcb5e7a9106aa642bd2e51b1135b15e1fceac690ddf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
